name = "ping_demo"
description = "Demo program to show how to write a simple ping program."
version = "0.0.1"
licenses = "Apache-2.0"

authors = ["Paul Jarrett"]
maintainers = ["Paul Jarrett <jarrett.paul.young@gmail.com>"]
maintainers-logins = ["pyjarrett"]

executables = ["ping_demo"]

[gpr-set-externals.'case(os)']
windows = { Ping_Demo_Platform = "windows" }
linux = { Ping_Demo_Platform = "linux" }
macos = { Ping_Demo_Platform = "macos" }
